I'm sorry, but an uncaught exception occurred.

Compiling ATL code at game/variables.rpy:68
  File "game/storyscript/firstchpt.rpy", line 465, in script
    "We can’t let a strong spirit like that relocate. That’d cause a bureaucratic mess that will doubtlessly end up with us pulling multiple all-nighters to handle."
  File "renpy/common/000window.rpy", line 98, in _window_auto_callback
    _window_show()
  File "renpy/common/000window.rpy", line 60, in _window_show
    renpy.with_statement(trans)
NameError: name 'blueapprove' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/storyscript/firstchpt.rpy", line 465, in script
    "We can’t let a strong spirit like that relocate. That’d cause a bureaucratic mess that will doubtlessly end up with us pulling multiple all-nighters to handle."
  File "C:\Users\J\Documents\renpy-7.1.3-sdk\renpy\ast.py", line 644, in execute
    statement_name("say")
  File "C:\Users\J\Documents\renpy-7.1.3-sdk\renpy\ast.py", line 45, in statement_name
    i(name)
  File "renpy/common/000window.rpy", line 98, in _window_auto_callback
    _window_show()
  File "renpy/common/000window.rpy", line 60, in _window_show
    renpy.with_statement(trans)
  File "C:\Users\J\Documents\renpy-7.1.3-sdk\renpy\exports.py", line 1481, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\J\Documents\renpy-7.1.3-sdk\renpy\display\core.py", line 2227, in do_with
    clear=clear)
  File "C:\Users\J\Documents\renpy-7.1.3-sdk\renpy\display\core.py", line 2672, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\Users\J\Documents\renpy-7.1.3-sdk\renpy\display\core.py", line 3059, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "C:\Users\J\Documents\renpy-7.1.3-sdk\renpy\display\core.py", line 531, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\J\Documents\renpy-7.1.3-sdk\renpy\display\core.py", line 531, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\J\Documents\renpy-7.1.3-sdk\renpy\display\core.py", line 531, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\J\Documents\renpy-7.1.3-sdk\renpy\display\core.py", line 531, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\J\Documents\renpy-7.1.3-sdk\renpy\display\core.py", line 531, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\J\Documents\renpy-7.1.3-sdk\renpy\display\core.py", line 531, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\J\Documents\renpy-7.1.3-sdk\renpy\display\core.py", line 521, in visit_all
    for d in self.visit():
  File "C:\Users\J\Documents\renpy-7.1.3-sdk\renpy\atl.py", line 574, in visit
    block = self.compile()
  File "C:\Users\J\Documents\renpy-7.1.3-sdk\renpy\atl.py", line 481, in compile
    block = self.atl.compile(self.context)
  File "C:\Users\J\Documents\renpy-7.1.3-sdk\renpy\atl.py", line 676, in compile
    statements = [ i.compile(ctx) for i in self.statements ]
  File "C:\Users\J\Documents\renpy-7.1.3-sdk\renpy\atl.py", line 889, in compile
    child = ctx.eval(expr)
  File "C:\Users\J\Documents\renpy-7.1.3-sdk\renpy\atl.py", line 246, in eval
    return eval(expr, renpy.store.__dict__, self.context)  # @UndefinedVariable
  File "<string>", line 1, in <module>
NameError: name 'blueapprove' is not defined

Windows-8-6.2.9200
Ren'Py 7.1.3.1092
SpIn 1.0
Thu Mar 14 22:36:30 2019
