I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 22, in script call
    call huntmodestart #Testing our hunt mode
  File "game/huntmode/hunt.rpy", line 124, in script call
    call huntmode
  File "game/huntmode/hunt.rpy", line 105, in script
    $calcchest = chest*10
  File "game/huntmode/hunt.rpy", line 105, in <module>
    $calcchest = chest*10
NameError: name 'chest' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 22, in script call
    call huntmodestart #Testing our hunt mode
  File "game/huntmode/hunt.rpy", line 124, in script call
    call huntmode
  File "game/huntmode/hunt.rpy", line 105, in script
    $calcchest = chest*10
  File "C:\Users\J\Documents\renpy-7.1.3-sdk\renpy\ast.py", line 881, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\J\Documents\renpy-7.1.3-sdk\renpy\python.py", line 1913, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/huntmode/hunt.rpy", line 105, in <module>
    $calcchest = chest*10
NameError: name 'chest' is not defined

Windows-8-6.2.9200
Ren'Py 7.1.3.1092
SpIn 1.0
Sun Mar 31 18:12:38 2019
